msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-05-28 12:15+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: French\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Language: fr\n"
"Language: fr_FR\n"

#: redbot/cogs/audio/core/events/dpy.py:34
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Vous avez essayer d'exécuter le serveur Lavalink d'Audio sur une architecture non supporté. Seulement les commandes relatives aux paramètres seront disponibles."

#: redbot/cogs/audio/core/events/dpy.py:68
msgid "No DJ role found. Disabling DJ mode."
msgstr "Aucun rôle DJ détecté. Désactivation du mode DJ."

#: redbot/cogs/audio/core/events/dpy.py:78
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr "`{user_input}` n'est pas une valeur valide pour `{command}`"

#: redbot/cogs/audio/core/events/dpy.py:84
msgid "Unable To Parse Argument"
msgstr "Impossible d'analyser l'argument"

#: redbot/cogs/audio/core/events/dpy.py:94
#: redbot/cogs/audio/core/events/dpy.py:102
msgid "Invalid Argument"
msgstr "Argument invalide"

#: redbot/cogs/audio/core/events/dpy.py:95
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr "L'argument que vous avez donné pour `{}` n'est pas valide : je m'attendais à `{}`."

#: redbot/cogs/audio/core/events/dpy.py:112
msgid "Invalid Environment"
msgstr "Environnement invalide"

#: redbot/cogs/audio/core/events/dpy.py:113
msgid "Connection to Lavalink has been lost."
msgstr "La connexion à Lavalink a été perdue."

#: redbot/cogs/audio/core/events/dpy.py:121
msgid "No Player Available"
msgstr "Aucun lecteur audio disponible"

#: redbot/cogs/audio/core/events/dpy.py:122
msgid "The bot is not connected to a voice channel."
msgstr "Le bot n'est pas connecté à un salon vocal."

#: redbot/cogs/audio/core/events/dpy.py:130
msgid "Unable to Get Track"
msgstr "Impossible d'obtenir la piste"

#: redbot/cogs/audio/core/events/dpy.py:131
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:68
msgid "Couldn't get a valid track."
msgstr "Impossible d'obtenir une piste valide."

#: redbot/cogs/audio/core/events/lavalink.py:87
msgid "Auto Play started."
msgstr "Lecture automatique démarrée."

#: redbot/cogs/audio/core/events/lavalink.py:102
msgid "Now Playing"
msgstr "Lecture en cours"

#: redbot/cogs/audio/core/events/lavalink.py:104
msgid "Track length: {length} | Requested by: {user}"
msgstr "Durée de la piste : {length} | Demandé par {user}"

#: redbot/cogs/audio/core/events/lavalink.py:125
msgid "Queue ended."
msgstr "File d’attente terminée."

#: redbot/cogs/audio/core/events/lavalink.py:167
msgid "Multiple Errors Detected"
msgstr "Multiples erreurs détectées"

#: redbot/cogs/audio/core/events/lavalink.py:168
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Fermeture du lecteur audio suite à de multiples erreurs détectées. Si cela persiste, veuillez informer le propriétaire du bot car le cog Audio peut être temporairement indisponible."

#: redbot/cogs/audio/core/events/lavalink.py:182
msgid "Track Stuck"
msgstr "Piste Bloquée"

#: redbot/cogs/audio/core/events/lavalink.py:187
msgid "Track Error"
msgstr "Erreur de la piste"

